site_name: Tomball Prep Handbook
site_url: https://handbook.tomballprep.org/
repo_url: https://github.com/tomballprep/handbook

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - toc.follow

nav:
  - Overview: index.md
  - Handbook:
      - Start here: handbook/index.md
      - Academics: handbook/academics.md
      - Athletics: handbook/athletics.md
  - Policies:
      - Index: policies/index.md
      - Privacy: policies/privacy.md
      - Terms: policies/terms.md
  - Support: support/index.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true